# Import Internetee style guide configuration
# This ensures all repositories use the same code style rules
inherit_from:
  - https://raw.githubusercontent.com/internetee/style-guide/master/.rubocop-ruby.yml

# Local overrides - exclude bin directory from analysis
AllCops:
  Exclude:
    - 'bin/**/*'

# Fix deprecated rule names for newer RuboCop versions
Style/MixedRegexpCaptureTypes:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Metrics/LineLength:
  Enabled: false

Layout/LineLength:
  Enabled: true
  Max: 120

Naming/UncommunicativeMethodParamName:
  Enabled: false

Naming/MethodParameterName:
  Enabled: true

# Fix documentation department warning
Style/Documentation:
  Enabled: false
