# Local RuboCop configuration based on Internetee style guide
# This avoids deprecated rule issues from the remote style guide

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - 'bin/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'config/initializers/version.rb'

# Layout
Layout/LineLength:
  Max: 120

Layout/IndentationWidth:
  Width: 2

Layout/EmptyLinesAroundMethodBody:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true

# Lint
Lint/UnusedMethodArgument:
  Enabled: false

Lint/MixedRegexpCaptureTypes:
  Enabled: true

# Metrics
Metrics/AbcSize:
  Max: 20

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 150

Metrics/ModuleLength:
  Max: 150

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'

# Naming
Naming/MethodParameterName:
  Enabled: true

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/IfUnlessModifier:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ReturnNil:
  Enabled: true

Style/Alias:
  EnforcedStyle: prefer_alias_method
