name: Qlty Code Quality

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  qlty:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'
        bundler-cache: true
        
    - name: Install Qlty
      run: gem install qlty
        
    - name: Run Qlty check
      run: qlty check
      
    - name: Run Qlty check with detailed output
      if: failure()
      run: qlty check --verbose
